name: RITArcade
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_login: ^5.0.0
  file_picker: ^10.1.9
  connectivity_plus: ^6.1.4
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  razorpay_flutter: ^1.4.0
  shared_preferences: ^2.5.3
  pdf: ^3.11.3
  cupertino_icons: ^1.0.8
  syncfusion_flutter_pdf: ^24.1.41
  cloudflare_r2: ^0.0.11
  path_provider: ^2.1.5
  crypto: ^3.0.6
  flutter_launcher_icons: ^0.14.4
  firebase_auth: ^5.6.2
  internet_connection_checker_plus: ^2.7.2
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter_launcher_icons:
  image_path: "assets/Xeroxshoplogo.jpg"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/Xeroxshoplogo.jpg"
  windows:
    generate: true
    image_path: "assets/Xeroxshoplogo.jpg"

flutter:
  uses-material-design: true
  # assets:
  assets:
    - assets/Xeroxshoplogo.jpg
    - assets/queue.png
    - assets/fonts/Itim-Regular.ttf
    - assets/ritlogo.jpg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
